# Generated by Django 5.1.6 on 2025-03-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_tag_post_published_date_alter_post_author_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
